# 存储巡查数据
mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/inspect?charset=utf8mb4&multiStatements=true&collation=utf8mb4_general_ci&parseTime=True&loc=UTC&timeout=10s&readTimeout=5s&writeTimeout=5s
# 查询的监控数据
prometheus:  
  - name: prometheus
    addr: http://172.17.3.80:9090
    accessId:
    accessSecret:
# 需要巡查的应用名
apps:
  - app-api
  - comments
  - egocron-master
  - egocron-worker
  - lizard-view
  - office-gateway
  - paolu-33
  - restart-collect-info
  - sheet-calc-tools
  - storage-gateway
  - storage-gateway-worker
  - svc-auth
  - svc-auth-worker
  - svc-convertor-mindmap-exporter
  - svc-convertor-officeio
  - svc-edit
  - svc-edit-worker-automention
  - svc-edit-worker-bigmosheet
  - svc-edit-worker-board
  - svc-edit-worker-form
  - svc-edit-worker-mindmap
  - svc-edit-worker-modoc
  - svc-edit-worker-mosheet
  - svc-edit-worker-presentation
  - svc-edit-worker-rdoc
  - svc-edit-worker-rsheet
  - svc-file
  - svc-file-doc-perception-worker
  - svc-file-drive
  - svc-file-drive-worker
  - svc-file-worker
  - svc-form
  - svc-form-worker
  - svc-history
  - svc-history-worker
  - svc-mns
  - svc-mns-worker
  - svc-nodejs-delta-maker
  - svc-nodejs-delta-parser
  - svc-nodejs-fc
  - svc-nodejs-fc-low
  - svc-nodejs-history-worker-actionhistory
  - svc-nodejs-history-worker-common
  - svc-nodejs-history-worker-modochistory
  - svc-nodejs-history-worker-rdochistory
  - svc-nodejs-history-worker-rsheethistory
  - svc-nodejs-sheet-calc
  - svc-nodejs-sheet-calc-local-queue
  - svc-notification-pull
  - svc-office-converter-java
  - svc-office-converter-java-file
  - svc-office-converter-rs
  - svc-provider-endpoint
  - svc-reaction-analyse
  - svc-reaction-consume
  - svc-reaction-http
  - svc-sdk-entrypoint
  - svc-search
  - svc-search-worker
  - svc-table
  - svc-table-worker
  - svc-tal-adapter
  - svc-thirdparty
  - svc-thirdparty-worker
  - svc-thumbnail
  - svc-tracking
  - svc-user
  - svc-user-worker
  - svc-utils
  - sync-tool
  - ws-gateway
  - ws-gateway-api
# 查询的监控指标
metrics:  
  - name: PodCount
    desc: 实例数
    query: count(kube_pod_info{namespace="default",pod=~"%s-\\w{8,}-\\w{4,}"})
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: CpuUsage
    desc: cpu使用核心数
    query: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="default",pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: CpuReq
    desc: CpuReq
    query: kube_pod_container_resource_requests{resource="cpu",namespace="default", pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: CpuLim
    desc: CpuLim
    query: kube_pod_container_resource_limits{resource="cpu", namespace="default", pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: MemUsage
    desc: MemUsage
    query: sum(container_memory_usage_bytes{pod=~"%s-\\w{8,}-\\w{4,}"}) by (pod)
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: MemRequest
    desc: MemRequest
    query: kube_pod_container_resource_requests{resource="memory", namespace="default", pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: MemLim
    desc: MemLim
    query: kube_pod_container_resource_limits{resource="memory", namespace="default", pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: max
  - name: CpuP90
    desc: CpuP90
    query: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="default",pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: quantile90
  - name: CpuP95
    desc: CpuP95
    query: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="default",pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: quantile95
  - name: CpuP99
    desc: CpuP99
    query: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="default",pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: quantile99
  - name: TotalMemLim
    desc: TotalMemLim
    query: sum(kube_pod_container_resource_limits{namespace="default", resource="memory"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: average
  - name: TotalCpuLim
    desc: TotalCpuLim
    query: sum(kube_pod_container_resource_limits{namespace="default", resource="cpu"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: average
  - name: TotalCpuReq
    desc: TotalCpuReq
    query: namespace_cpu:kube_pod_container_resource_requests:sum{namespace="default"}
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: average
  - name: TotalMemRequest
    desc: TotalMemRequest
    query: namespace_memory:kube_pod_container_resource_requests:sum{namespace="default"}
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: average
  - name: TotalPodCount
    desc: TotalPodCount
    query: count(node_namespace_pod:kube_pod_info:{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: average
  - name: AppGoroutine
    desc: AppGoroutine
    query: go_goroutines{app=~"^%s$"}
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppHandle
    desc: 应用句柄数
    query: process_open_fds{app=~"^%s$"}
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppGC
    desc: 应用GC
    query: go_gc_duration_seconds{app=~"^%s$"}
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppHTTPServerQPS
    desc: http服务端QPS
    query: irate(ego_server_handle_seconds_count{app=~"^%s$", type="http"}[5m])
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppGrpcServerQPS
    desc: grpc服务端qps
    query: irate(ego_server_handle_seconds_count{app=~"^%s$", type="unary"}[5m])
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppGrpcClientQPS
    desc: grpc客户端qps
    query: irate(ego_client_handle_seconds_count{app=~"^%s$", type="unary"}[5m])
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppPodCPU
    desc: 应用CPU使用率
    query: irate(container_cpu_usage_seconds_total{pod=~"%s-\\w{8,}-\\w{4,}"}[1m])
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppPodRss
    desc: 应用RSS内存
    query: container_memory_rss{container =~"^%s$"}
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppPodRssUseRate
    desc: 应用RSS使用率
    query: sum(container_memory_rss{container =~"^%s$"}) by (container)/ sum(container_spec_memory_limit_bytes{container =~"^%s$"}) by (container) * 100
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppPodDisk
    desc: 应用磁盘使用量
    query: sum(container_fs_usage_bytes{container=~"^%s$"})
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppPodDiskUseRate
    desc: 应用磁盘利用率
    query: sum(container_fs_usage_bytes{container=~"^%s$"}) / sum(container_fs_limit_bytes{container=~"^%s$"}) * 100
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: AppPodCount
    desc: 应用实例数
    query: count(ego_build_info{app=~"^%s$"})
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: MemP90
    desc: MemP90
    query: sum(container_memory_usage_bytes{pod=~"%s-\\w{8,}-\\w{4,}"}) by (pod)
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: quantile90
  - name: MemP95
    desc: MemP95
    query: container_memory_usage_bytes{pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: quantile95
  - name: MemP99
    desc: MemP99
    query: sum(container_memory_usage_bytes{pod=~"%s-\\w{8,}-\\w{4,}"}) by (pod)
    type: prometheus
    typeName: prometheus
    targetType: svc
    aggrFunc: quantile99
  - name: TotalCpuP95
    desc: 总CPU P95
    query: sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_irate{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: quantile95
  - name: TotalMemP95
    desc: 总内存 P95
    query: sum(container_memory_usage_bytes{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: quantile95
  - name: TotalCpuMax
    desc: 总CPU最大使用量
    query: sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_irate{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: max
  - name: TotalMemMax
    desc: 总内存最大使用量
    query: sum(container_memory_usage_bytes{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: max
  - name: TotalPodCountMax
    desc: 总实例数最大值
    query: count(kube_pod_info{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: max
  - name: TotalPodCountP95
    desc: 总实例数P95
    query: count(kube_pod_info{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: quantile95
  - name: TotalDiskMax
    desc: 总硬盘最大使用量
    query: sum(container_fs_usage_bytes{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: max
  - name: TotalDiskP99
    desc: 总硬盘使用量P99
    query: sum(container_fs_usage_bytes{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: quantile99
  - name: TotalDiskP95
    desc: 总硬盘使用量P95
    query: sum(container_fs_usage_bytes{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: quantile95
  - name: TotalDiskP90
    desc: 总硬盘使用量P90
    query: sum(container_fs_usage_bytes{namespace="default"})
    type: prometheus
    typeName: prometheus
    targetType: none
    aggrFunc: quantile90
  - name: AppPodRssP95
    desc: RSS p95
    query: container_memory_rss{pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: quantile95
  - name: AppPodMem
    desc: max(内存大小)
    query: container_memory_usage_bytes{pod=~"%s-\\w{8,}-\\w{4,}"}
    type: prometheus
    typeName: prometheus
    targetType: pod
    aggrFunc: max
  - name: pvuv
    desc: 整体访问PV,UV
    query: "*| select approx_distinct(x_forward_for) as uv ,count(1) as pv"
    type: other
    targetType: none
  - name: reqSuccRate
    desc: 查询整体请求成功率(状态码小于500的)
    query: "* and not host: track.shimo.im | select round(sum(case when status < 500 then 1 else 0 end) * 100.0 / count(1), 3) as count"
    type: other
    targetType: none
  - name: reqLatencyAvg
    desc: 查询整体平均耗时
    query: "status < 500 and not proxy_upstream_name:default-smpro-svc-sdk-entrypoint-9001 and not proxy_upstream_name:default-smpro-ws-server-v2-9001 and not proxy_upstream_name:default-smpro-kong-plugin-8000 and not proxy_upstream_name: default-smpro-svc-aud"
    type: other
    targetType: none
  - name: reqLatencyQuantile
    desc: 查询整体耗时按TP90,95,99 分类
    query: "status < 500 and not proxy_upstream_name:default-smpro-svc-sdk-entrypoint-9001 and not proxy_upstream_name:default-smpro-ws-server-v2-9001 and not proxy_upstream_name:default-smpro-kong-plugin-8000 and not proxy_upstream_name: default-smpro-svc-aud"
    type: other
    targetType: none
  - name: reqLatencyQuantileBySvc
    desc: 查询后端请求耗时，按服务名分组，过滤结果p95大于1的，按p95倒序排名
    query: "status < 500 and not proxy_upstream_name:default-smpro-svc-sdk-entrypoint-9001 and not proxy_upstream_name:default-smpro-ws-server-v2-9001 and not proxy_upstream_name:default-smpro-kong-plugin-8000 and not proxy_upstream_name: default-smpro-svc-aud"
    type: other
    targetType: svc
  - name: reqTraffic
    desc: 查询出入网流量
    query: "* | select sum(body_bytes_sent)*8/86400 as net_out, sum(request_length)*8/86400 as net_in"
    type: other
    targetType: none
cron:
  prometheus:
    enableDistributedTask: false
    enableImmediatelyRun: false
    enableSeconds: true
    spec: "5 0 0 * * *"
    delayExecType: queue


