{
 "title": "应用峰值表格大盘-mdp",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "panels": [
  { "title": "应用资源统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "应用资源消耗统计",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  a.time AS \"time\",\n\ta.target_name,\n\tmax(a.val) / max(b.val) as \"CPURateMAX\"\nFROM\n\treport_measure a\n\tJOIN report_measure b ON a.target_name = b.target_name\nWHERE\n\ta.metric = 'CpuUsage'\n\tAND b.metric = 'CpuLim'\n\tAND $__unixEpochFilter(a.time)\n\tAND $__unixEpochFilter(b.time)\nGROUP BY\n\ta.target_name"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppPodCPU\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'CpuUsage'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppPodRss\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppPodRss'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT \n  a.time AS \"time\",\n\ta.target_name,\n\tmax(a.val) / max(b.val) as \"MemRateMAX\"\nFROM\n\treport_measure a\n\tJOIN report_measure b ON a.target_name = b.target_name\nWHERE\n\ta.metric = 'AppPodMem'\n\tAND b.metric = 'MemLim'\n\tAND $__unixEpochFilter(a.time)\n\tAND $__unixEpochFilter(b.time)\nGROUP BY\n\ta.target_name"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppPodDiskUseRate\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppPodDiskUseRate'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppPodDisk\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppPodDisk'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppHandle\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'AppHandle'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"CpuLim\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'CpuLim'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"PodCount\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'PodCount'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"MemLim\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'MemLim'\nGROUP BY target_name\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"MemP95\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'MemP95'\nGROUP BY target_name\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"CPUP95\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'CpuP95'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"CpuReq\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'CpuReq'\nGROUP BY target_name\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"MemReq\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'MemRequest'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  avg(val) AS \"AppHTTPServerQPS\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'AppHTTPServerQPS'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  avg(val) AS \"AppGrpcServerQPS\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'AppGrpcServerQPS'\nGROUP BY target_name\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,$__interval),\n  max(val) AS \"AppGrpcClientQPS\",\n  target_name\nFROM report_measure\nWHERE\n$__unixEpochFilter(time) AND\n  metric = 'AppGrpcClientQPS'\nGROUP BY 1, target_name\nORDER BY $__unixEpochGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppPodMem\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppPodMem'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"AppPodRssP95\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppPodRssP95'\nGROUP BY target_name\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  max(val) AS \"netstatTWCnt\",\n  target_name\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'netstatTWCnt'\nGROUP BY target_name\nORDER BY time"
    }
   ]
  },
  { "title": "Go 性能", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Goroutine",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  target_name,\n  max(val) AS \"Goroutine\"\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppGoroutine'\nGROUP BY target_name\nORDER BY time"
    }
   ]
  },
  {
   "title": "GC",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  val AS \"GC\",\n  target_name AS \"target_name\"\nFROM report_measure\nWHERE\n  $__unixEpochFilter(time) AND\n  metric = 'AppGC'\nGROUP BY target_name\nORDER BY time"
    }
   ]
  }
 ]
}